In [11]:

import numpy as np
from scipy.spatial.distance import cdist

In [8]:

n_boids = 10
too_close_radius = 4
visible_radius = 48

In [9]:

avoid_weight = 1
align_weight = 1
center_weight = 1

In [12]:

boid_poss = np.random.uniform(-n_boids/2, n_boids/2, (n_boids, 2))
boid_vels = np.random.uniform(-1, 1, (n_boids, 2))

In [13]:

distances = cdist(boid_poss, boid_poss)

In [14]:

# pairs of indices that are too close
too_close_neighbors = np.where(distances[0] < too_close_radius)
visible_neighbors = np.where(distances[0] < visible_radius)

In [21]:
boid_poss[0, None] - boid_poss[too_close_neighbors]

array([[ 0.        ,  0.        ],
       [ 0.58454783,  3.92151883],
       [-1.55439236, -1.66521143],
       [-2.4181025 ,  3.1474699 ]])

In [20]:
boid_poss[0] - boid_poss[1]

array([0.58454783, 3.92151883])

In [80]:
distances[0][too_close_neighbors]

array([0.        , 3.23179797, 3.78423245, 3.14671121])

In [65]:
np.array([np.where(distances[i] < too_close_radius) for i in range(len(distances))])

/var/folders/p5/52jmynx13jdctdpd69bl3hjw0000gq/T/ipykernel_94393/2392263539.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([np.where(distances[i] < too_close_radius) for i in range(len(distances))])


array([[array([0, 1, 4, 6])],
       [array([0, 1, 3, 4, 6])],
       [array([2, 4, 6, 8])],
       [array([1, 3, 4, 6, 7])],
       [array([0, 1, 2, 3, 4, 6, 8])],
       [array([5, 7])],
       [array([0, 1, 2, 3, 4, 6, 8])],
       [array([3, 5, 7])],
       [array([2, 4, 6, 8, 9])],
       [array([8, 9])]], dtype=object)

In [56]:
sums

array([11., 14., 20., 21., 24., 12., 24., 15., 29., 17.])